name: comment-regularly
on:
  schedule:
    - cron: '55 05 * * 1,5'
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pygments
      - name: Run the script to leave a comment
        shell: bash
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
        run: |
          python3 cli.py -vvv --no-keyring --double-plus \
                         --token "$VK_TOKEN"
