name: comment-regularly
on:
  schedule:
    - cron: '45 05 * * 1,5'
  workflow_dispatch:
    inputs:
      group_id:
        description: 'VK group id'
        required: false
        default: 'stawclub'
      time:
        description: 'Expect new post at'
        required: false
        default: '06:00'
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pygments
      - name: Run the script to leave a comment
        shell: bash
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
        run: |
          python3 cli.py -vvv --no-keyring --double-plus --github-workaround \
                         --token "$VK_TOKEN" \
                         --group-id "${{ github.event.inputs.group_id }}" \
                         --posted-at "${{ github.event.inputs.time }}"
